### ISSUE TITLE
Skráarnöfn eftir tímaröð?

### ISSUE THREAD

**Issue by viktorsmari** [piratar/fundargerdir#3]
Sælar @elinpirati @ElsaPirati 

Ég sé að þetta gengur prýðisvel hjá ykkur, en ég var með nörda pælingu varðandi nöfnin og röðun.

Núna "sorterast" þetta svona hjá okkur:
![2019-12-10_10-25-17](https://user-images.githubusercontent.com/1689020/70516520-6d5a3100-1b37-11ea-9aa5-9151fececa77.png)

Ef að okkur langar að hafa þetta í tímaröð, þá er líklega besta leiðin sé að nota `YYYY-MM-DD` formattið.

* Þá myndi skráarnafn fundar 13 des þessa árs vera `2019-12-13.md`

Þetta er líklega uppáhalds format tölvunörða því þetta tryggir rétta tímaröðun eftir nafni :nerd_face: 

Þetta er ekki forgangsatriði, bara pæling! :neckbeard:

**Comment by ElsaPirati** [comment]
Ég tók eftir þessu líka í gær og er sammála þér. Er nokkuð mál að breyta nafni á skrá? Ég get farið í það þegar ég set inn næstu fundargerð.

**Comment by viktorsmari** [comment]
Til að breyta nafni á skjali, þá þarf að:
* Fyrst velja skjalið sem á að breyta.
* Ýta á blýantinn eftir að búið er að velja skjalið:

**Skjáskot 1**
![2019-12-10_12-19-50](https://user-images.githubusercontent.com/1689020/70525338-6804e280-1b47-11ea-9b62-b6866ba3b358.png)


Þá birtist þetta þar sem hægt er að breyta nafninu:

**Skjáskot 2**
![2019-12-10_12-19-57](https://user-images.githubusercontent.com/1689020/70525337-6804e280-1b47-11ea-8d7b-c8aa2a6b2ee0.png)
